-- 1. Create the products table
CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    price TEXT,
    image TEXT,
    category TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enable RLS (Row Level Security) - Optional but recommended
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- 3. Create a public access policy
CREATE POLICY "Allow public read access" ON products FOR SELECT USING (true);
CREATE POLICY "Allow authenticated changes" ON products FOR ALL USING (true); -- Simplified for this setup

-- 4. Seed with existing data (Extracted from menuData.ts)
INSERT INTO products (name, price, image, category) VALUES
('Beylerbeyi Göbek Rakı', '100cl: 3200 TL | 70cl: 2400 TL | 50cl: 1800 TL | 35cl: 1300 TL | 20cl: 900 TL', 'alkol_beylerbeyi_gobek_raki.png', 'alkol_'),
('Johnnie Walker Black Label', '100cl: 4200 TL | 70cl: 3200 TL | 50cl: 2500 TL | 35cl: 1800 TL', 'alkol_black_label_viski.png', 'alkol_'),
('Bomonti Filtresiz', '230 TL', 'alkol_bomonti_bira.png', 'alkol_'),
('Bulldog Gin 70cl', '2800 TL', 'alkol_bulldog_gin_70.png', 'alkol_'),
('Carlsberg', '220 TL', 'alkol_carlsberg.png', 'alkol_'),
('Chivas Regal 12 YO', '100cl: 4500 TL | 70cl: 3500 TL | 50cl: 2800 TL | 35cl: 2000 TL', 'alkol_chivas_regal_viski.png', 'alkol_'),
('Corona Bira', '250 TL', 'alkol_corona_bira.png', 'alkol_'),
('Double Rakı', '450 TL', 'alkol_double_raki.png', 'alkol_'),
('Double Viski', '650 TL', 'alkol_double_viski.png', 'alkol_'),
('Efe Gold Rakı', '100cl: 2900 TL | 70cl: 2100 TL | 50cl: 1600 TL | 35cl: 1100 TL', 'alkol_efe_gold_raki.png', 'alkol_'),
('Glen Grant 70cl', '2600 TL', 'alkol_glent_grant_70.png', 'alkol_'),
('Gordon Gin', '70cl: 2200 TL | 35cl: 1200 TL', 'alkol_gordon_gin.png', 'alkol_'),
('İstanblue Vodka', '100cl: 2200 TL | 70cl: 1700 TL | 50cl: 1300 TL | 35cl: 950 TL', 'alkol_istanblue_vodka.png', 'alkol_'),
('Kadeh Şarap', '350 TL', 'alkol_kadeh_sarap.png', 'alkol_'),
('Olmeca Tekila', '70cl Silver: 2500 TL | 35cl Gold: 1350 TL', 'alkol_olmeca_tekila.png', 'alkol_'),
('Tek Rakı', '250 TL', 'alkol_tek_raki.png', 'alkol_'),
('Tekirdağ Altın Seri', '100cl: 3000 TL | 70cl: 2200 TL | 50cl: 1700 TL | 35cl: 1200 TL | 20cl: 850 TL', 'alkol_tekirdag_altin_raki.png', 'alkol_'),
('Tekirdağ Göbek Rakı', '100cl: 3200 TL | 70cl: 2400 TL | 50cl: 1800 TL | 35cl: 1300 TL', 'alkol_tekirdag_gobek_raki.png', 'alkol_'),
('Tuborg Bira', '200 TL', 'alkol_tuborg.png', 'alkol_'),
('Yakut / Dere Şarap', '1800 TL', 'alkol_yakutdere_sarap.png', 'alkol_'),
('Yeni Rakı', '100cl: 2800 TL | 70cl: 2000 TL | 50cl: 1500 TL | 3500 TL', 'alkol_yeni_raki.png', 'alkol_'),
('Acı Soslu Tavuk', '480 TL', 'ana_yemek_acisoslutavuk.png', 'ana_yemek_'),
('Antrikot Izgara', '900 TL', 'ana_yemek_antrikot.jpg', 'ana_yemek_'),
('Cafe de Paris Antrikot', '1.000 TL', 'ana_yemek_cafedeparis_antrikot.png', 'ana_yemek_'),
('Çıtır Mantı', '380 TL', 'ana_yemek_citir_manti.png', 'ana_yemek_'),
('Et Çökertme', '700 TL', 'ana_yemek_et_cokertme.png', 'ana_yemek_'),
('İçli Köfte', '320 TL', 'ana_yemek_icli_kofte.png', 'ana_yemek_'),
('Kiremitte Kaşarlı Et', '750 TL', 'ana_yemek_kiremitte_et_kasarli.png', 'ana_yemek_'),
('Kiremitte Kaşarlı Tavuk', '520 TL', 'ana_yemek_kiremitte_tavuk_kasarli.webp', 'ana_yemek_'),
('Mantar Soslu Tavuk', '480 TL', 'ana_yemek_mantarsoslu_tavuk.png', 'ana_yemek_'),
('Ev Mantısı', '350 TL', 'ana_yemek_manti.png', 'ana_yemek_'),
('Sac Kavurma', '680 TL', 'ana_yemek_sac_kavurma.png', 'ana_yemek_'),
('Tavuk Şinitzel', '450 TL', 'ana_yemek_sinitzel.png', 'ana_yemek_'),
('Barbun Tava', '700 TL', 'balik_barbun.png', 'balik_'),
('İstavrit Tava', '500 TL', 'balik_istavrit.png', 'balik_'),
('Tereyağlı Karides', '600 TL', 'balik_karides.png', 'balik_'),
('Levrek Buğulama', '750 TL', 'balik_levrek_buglama.png', 'balik_'),
('Kiremitte Kaşarlı Levrek', '800 TL', 'balik_levrek_kasarli.png', 'balik_'),
('Mezgit Tava', '650 TL', 'balik_mezgit.png', 'balik_'),
('Somon Buğulama', '800 TL', 'balik_somon_buglama.png', 'balik_'),
('Kiremitte Kaşarlı Somon', '850 TL', 'balik_somon_kasarli.webp', 'balik_'),
('Zargan Tava', '550 TL', 'balik_zargan.png', 'balik_'),
('Kuzu Pirzola', '850 TL', 'izgara__kuzu.png', 'izgara_'),
('Akçaabat Köfte', '600 TL', 'izgara_akcaabat_kofte.png', 'izgara_'),
('Levrek Izgara', '700 TL', 'izgara_levrek.png', 'izgara_'),
('Somon Izgara', '800 TL', 'izgara_somon.png', 'izgara_'),
('Tavuk Izgara', '450 TL', 'izgara_tavuk.png', 'izgara_'),
('Hamburger Menü', '400 TL', 'fast_food_hamburger.png', 'fast_food_'),
('Kaşarlı Tost', '180 TL', 'fast_food_kasarli_tost.png', 'fast_food_'),
('Sandviç Çeşitleri', '220 TL', 'fast_food_sandvic.png', 'fast_food_'),
('Sucuklu Tost', '200 TL', 'fast_food_sucuklu_tost.png', 'fast_food_'),
('Patates Kızartması', '150 TL', 'fastfood_french_fries.png', 'fast_food_'),
('Gözleme Peynirli', '200 TL', 'gozleme_beyaz_peynir.png', 'gozleme_'),
('Gözleme Kaşarlı', '220 TL', 'gozleme_kasarli.png', 'gozleme_'),
('Gözleme Patatesli', '210 TL', 'gozleme_patates.png', 'gozleme_'),
('Ayran', '80 TL', 'icecek_ayran.png', 'icecek_'),
('Demleme Çay', '40 TL', 'icecek_cay.png', 'icecek_'),
('Coca Cola', '100 TL', 'icecek_cola.png', 'icecek_'),
('Fanta / Sprite', '100 TL', 'icecek_fanta.png', 'icecek_'),
('Fuse Tea', '100 TL', 'icecek_fuse_tea.png', 'icecek_'),
('Meyveli Soda', '80 TL', 'icecek_meyveli_soda.png', 'icecek_'),
('Redbull', '180 TL', 'icecek_redbull.png', 'icecek_'),
('Sade Soda', '60 TL', 'icecek_sade_soda.png', 'icecek_'),
('Şalgam Suyu', '80 TL', 'icecek_salgam.png', 'icecek_'),
('Sprite', '100 TL', 'icecek_sprite.png', 'icecek_'),
('Tonik', '100 TL', 'icecek_tonik_1.png', 'icecek_'),
('Türk Kahvesi', '100 TL', 'icecek_turk_kahvesi.png', 'icecek_'),
('Kahvaltı Patatesi', '180 TL', 'kahvalti_french_fries.png', 'kahvalti_'),
('Kuymak', '250 TL', 'kahvalti_kuymak.png', 'kahvalti_'),
('Serpme Kahvaltı (2 Kişilik)', '1.200 TL', 'kahvalti_masa.jpg', 'kahvalti_'),
('Menemen', '200 TL', 'kahvalti_menemen.png', 'kahvalti_'),
('Karışık Kahvaltı Tabağı', '450 TL', 'kahvalti_mix_tabak.png', 'kahvalti_'),
('Kaşarlı Omlet', '220 TL', 'kahvalti_omlet_kasarli.png', 'kahvalti_'),
('Sade Omlet', '180 TL', 'kahvalti_omlet.png', 'kahvalti_'),
('Sigara Böreği', '180 TL', 'kahvalti_sigara_boregi.png', 'kahvalti_'),
('Soğan Halkası', '160 TL', 'kahvalti_sogan_halkasi.png', 'kahvalti_'),
('Sosis Tava', '240 TL', 'kahvalti_sosis.png', 'kahvalti_'),
('Sucuklu Yumurta', '280 TL', 'kahvalti_sucuklu_yumurta.png', 'kahvalti_'),
('Tabldot Kahvaltı', '350 TL', 'kahvalti_tablot.jpg', 'kahvalti_'),
('Penne Arrabbiata', '350 TL', 'makarna_arabiata.png', 'makarna_'),
('Makarna Bolonez', '380 TL', 'makarna_bolonez.png', 'makarna_'),
('Fettucini Alfredo', '400 TL', 'makarna_fettucini.png', 'makarna_'),
('Makarna Napoliten', '360 TL', 'makarna_napoliten.png', 'makarna_'),
('Penne Makarna', '320 TL', 'makarna_penne.png', 'makarna_'),
('Acılı Ezme', '220 TL', 'meze_acili_ezme.png', 'meze_'),
('Arnavut Ciğeri', '350 TL', 'meze_arnavut_ciger.png', 'meze_'),
('Atom', '220 TL', 'meze_atom.png', 'meze_'),
('Deniz Börülcesi', '220 TL', 'meze_deniz_borulcesi.png', 'meze_'),
('Fava', '220 TL', 'meze_fava.png', 'meze_'),
('Haydari', '220 TL', 'meze_haydari.png', 'meze_'),
('Humus', '220 TL', 'meze_humus.png', 'meze_'),
('Karides Marin', '380 TL', 'meze_karides_marin.png', 'meze_'),
('Köpoğlu', '220 TL', 'meze_kopeoglu.png', 'meze_'),
('Kuru Cacık', '180 TL', 'meze_kuru_cacik.png', 'meze_'),
('Levrek Marin', '380 TL', 'meze_levrek_marin.png', 'meze_'),
('Paşa Meze Özel', '250 TL', 'meze_pasa.png', 'meze_'),
('Şakşuka', '220 TL', 'meze_saksuka.png', 'meze_'),
('Sebzeli Mantar', '240 TL', 'meze_sebzeli_mantar.png', 'meze_'),
('Somon Marin', '380 TL', 'meze_somon_marin.png', 'meze_'),
('Tarator', '220 TL', 'meze_tarator.png', 'meze_'),
('Zeytinyağlı Fasulye', '220 TL', 'meze_zeytinyagli_fasulye.png', 'meze_'),
('Zeytinyağlı Pilaki', '220 TL', 'meze_zeytinyagli_pilaki.png', 'meze_'),
('Akdeniz Salata', '250 TL', 'salata_akdeniz.png', 'salata_'),
('Çoban Salata', '220 TL', 'salata_coban.png', 'salata_'),
('Karışık Mevsim Salata', '220 TL', 'salata_karisik.png', 'salata_'),
('Mevsim Salata', '200 TL', 'salata_mevsim.png', 'salata_'),
('Sezar Salata', '300 TL', 'salata_sezar.png', 'salata_'),
('Yeşil Salata', '200 TL', 'salata_yesil.png', 'salata_'),
('Şezlong & Şemsiye', '250 TL', 'sezlong.png', 'sezlong'),
('Mevsim Meyveleri Tabağı', '450 TL', 'tatli_meyve_tabagi.png', 'tatli_');
